export type Session = {
  id: string;
  title: string;
  description: string;
  date: string; // ISO format e.g. 2026-10-25
  startTime: string; // e.g. 09:00
  endTime: string; // e.g. 10:00
  trackId: string;
  speakerId: string;
  room: string;
};

export const sessions: Session[] = [
  // Day 1
  {
    id: "ses_1",
    title: "Opening Keynote: The Future of Distributed AI Systems",
    description: "Kick off the event with an exploration of scalable LLMs.",
    date: "2026-10-25",
    startTime: "09:00",
    endTime: "10:30",
    trackId: "technical",
    speakerId: "spk_1",
    room: "Main Auditorium",
  },
  {
    id: "ses_2",
    title: "Building Zero-Downtime Architectures",
    description: "Learn how to design resilient microservices in the cloud.",
    date: "2026-10-25",
    startTime: "11:00",
    endTime: "12:00",
    trackId: "technical",
    speakerId: "spk_2",
    room: "Hall A",
  },
  {
    id: "ses_3",
    title: "Product Management in High-Stakes Environments",
    description: "Bridging engineering and business for high-impact delivery.",
    date: "2026-10-25",
    startTime: "11:00",
    endTime: "12:00",
    trackId: "managerial",
    speakerId: "spk_5",
    room: "Hall B",
  },
  {
    id: "ses_4",
    title: "From Idea to Series A: The Founder's Journey",
    description: "Insights into early stage fundraising and scaling.",
    date: "2026-10-25",
    startTime: "13:00",
    endTime: "14:00",
    trackId: "entrepreneurial",
    speakerId: "spk_3",
    room: "Main Auditorium",
  },
  {
    id: "ses_5",
    title: "Implementing Zero-Trust from Scratch",
    description: "A practical guide to securing modern architectures.",
    date: "2026-10-25",
    startTime: "14:30",
    endTime: "15:30",
    trackId: "technical",
    speakerId: "spk_6",
    room: "Hall A",
  },
  
  // Day 2
  {
    id: "ses_6",
    title: "Navigating the Unknown: Autonomous Systems",
    description: "Deep dive into robotics and human-robot interaction.",
    date: "2026-10-26",
    startTime: "09:30",
    endTime: "10:30",
    trackId: "technical",
    speakerId: "spk_4",
    room: "Main Auditorium",
  },
  {
    id: "ses_7",
    title: "Scaling Agile Beyond the Development Team",
    description: "How to bring agile methodologies to the entire organization.",
    date: "2026-10-26",
    startTime: "11:00",
    endTime: "12:00",
    trackId: "managerial",
    speakerId: "spk_8",
    room: "Hall B",
  },
  {
    id: "ses_8",
    title: "The Startup CTO's Survival Guide",
    description: "Building scalable technical foundations under pressure.",
    date: "2026-10-26",
    startTime: "13:00",
    endTime: "14:00",
    trackId: "entrepreneurial",
    speakerId: "spk_10",
    room: "Hall C",
  },
  {
    id: "ses_9",
    title: "AI in Healthcare: Ethical and Practical Challenges",
    description: "Optimizing healthcare workflows with machine learning.",
    date: "2026-10-26",
    startTime: "14:30",
    endTime: "15:30",
    trackId: "technical",
    speakerId: "spk_7",
    room: "Main Auditorium",
  },
  {
    id: "ses_10",
    title: "Designing for Everyone: Accessibility First",
    description: "User-centric design principles for modern web applications.",
    date: "2026-10-26",
    startTime: "16:00",
    endTime: "17:00",
    trackId: "managerial",
    speakerId: "spk_9",
    room: "Hall B",
  },

  // Day 3
  {
    id: "ses_11",
    title: "Smart Contract Security Best Practices",
    description: "Securing decentralized applications in Web3.",
    date: "2026-10-27",
    startTime: "09:30",
    endTime: "10:30",
    trackId: "technical",
    speakerId: "spk_11",
    room: "Hall A",
  },
  {
    id: "ses_12",
    title: "Managing Distributed Engineering Teams",
    description: "Operational excellence in a remote-first world.",
    date: "2026-10-27",
    startTime: "11:00",
    endTime: "12:00",
    trackId: "managerial",
    speakerId: "spk_12",
    room: "Hall B",
  },
  {
    id: "ses_13",
    title: "Quantum Computing: Beyond the Hype",
    description: "Practical applications of quantum algorithms.",
    date: "2026-10-27",
    startTime: "13:00",
    endTime: "14:00",
    trackId: "technical",
    speakerId: "spk_13",
    room: "Main Auditorium",
  },
  {
    id: "ses_14",
    title: "Marketing for Engineers: Telling Your Product's Story",
    description: "Data-driven marketing strategies for tech companies.",
    date: "2026-10-27",
    startTime: "14:30",
    endTime: "15:30",
    trackId: "entrepreneurial",
    speakerId: "spk_15",
    room: "Hall C",
  },
  {
    id: "ses_15",
    title: "Building Thriving Open Source Communities",
    description: "Fostering developer experience and open-source contributions.",
    date: "2026-10-27",
    startTime: "16:00",
    endTime: "17:00",
    trackId: "managerial",
    speakerId: "spk_14",
    room: "Hall B",
  },
];
