"use client";

import * as React from "react";
import { Html5Qrcode } from "html5-qrcode";
import toast from "react-hot-toast";
import { Button } from "@/components/ui/button";
import { SectionWrapper } from "@/components/ui/section-wrapper";
import { cn } from "@/lib/utils";

export default function MemberScanPage() {
  const [scanning, setScanning] = React.useState(false);
  const scannerRef = React.useRef<Html5Qrcode | null>(null);

  const startScanner = async () => {
    const reader = new Html5Qrcode("qr-reader");
    scannerRef.current = reader;

    try {
      await reader.start(
        { facingMode: "environment" },
        { fps: 10, qrbox: { width: 250, height: 250 } },
        (decodedText) => handleScan(decodedText),
        () => {}
      );
      setScanning(true);
    } catch (err) {
      console.error("Scanner start error:", err);
      toast.error("Could not access camera. Check permissions.");
    }
  };

  const stopScanner = async () => {
    if (scannerRef.current) {
      try {
        await scannerRef.current.stop();
        scannerRef.current.clear();
      } catch { /* already stopped */ }
      scannerRef.current = null;
    }
    setScanning(false);
  };

  React.useEffect(() => {
    return () => {
      if (scannerRef.current) {
        scannerRef.current.stop().catch(() => {});
      }
    };
  }, []);

  const handleScan = (decodedText: string) => {
    if (decodedText.startsWith("http://") || decodedText.startsWith("https://")) {
      toast.success("QR Scanned! Loading form...");
      stopScanner().then(() => {
        window.location.href = decodedText;
      });
    } else {
      toast.error("Invalid QR code format. Please scan a valid ScantoAttend URL.");
    }
  };

  return (
    <SectionWrapper
      withWatermark
      className="pt-20 md:pt-32 pb-20 min-h-[85vh] flex items-center justify-center"
    >
      <div className="relative w-full max-w-md mx-auto bg-brand-black/40 backdrop-blur-md border border-brand-muted/20 p-8 rounded-2xl shadow-2xl text-center flex flex-col items-center gap-6 overflow-hidden">
        <div className="absolute -top-40 -left-40 w-80 h-80 bg-brand-lime/5 rounded-full blur-[100px] pointer-events-none" />

        <div>
          <h1 className="text-3xl font-display uppercase tracking-tight mb-2 text-brand-white">
            Scan Attendance QR
          </h1>
          <p className="text-brand-muted text-sm max-w-sm mx-auto">
            Point your camera at the session QR code generated by the administrator.
          </p>
        </div>

        <div className="w-full flex flex-col items-center gap-4">
          {!scanning ? (
            <Button onClick={startScanner} className="w-full py-6 text-base" size="lg">
              Start Scanning
            </Button>
          ) : (
            <Button variant="destructive" onClick={stopScanner} className="w-full py-6 text-base" size="lg">
              Stop Scanning
            </Button>
          )}

          <div
            id="qr-reader"
            className={cn(
              "w-full max-w-sm overflow-hidden rounded-xl border border-brand-muted/20 bg-brand-black/25",
              !scanning && "hidden"
            )}
          />
        </div>
      </div>
    </SectionWrapper>
  );
}
